version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
    labels:
      - "pr:chore"
    commit-message:
      prefix: "chore"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    labels:
      - "pr:chore"
    commit-message:
      prefix: "chore"
