version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: cron
      cronjob: "0 9 3,18 * *"
    labels:
      - "pr:chore"
    commit-message:
      prefix: "chore"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: cron
      cronjob: "0 9 3,18 * *"
    labels:
      - "pr:chore"
    commit-message:
      prefix: "chore"
