#!/bin/bash
# Execute lint to spot code mistakes.

cd "$(dirname "$0")/.."

export files="$(find /workspaces/ha-custom-universal-media-player/custom_components -name '*.py')"
echo '================================================='
echo '=                FILES CHANGED                  ='
echo '================================================='
if [ -z "$files" ] ; then
  echo "No python file changed.\n"
  exit
fi
printf "%s\n" $files
echo "=============="
echo "LINT with ruff"
echo "=============="
prek run ruff-check --files $files
echo "================"
echo "LINT with pylint"
echo "================"
pylint_files=$(echo "$files" | grep -v '^tests.*')
if [ -z "$pylint_files" ] ; then
  echo "Only test files changed. Skipping\n"
  exit
fi
pylint $pylint_files
echo
